{% set name = "enpt_enmapboxapp" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/enpt_enmapboxapp-{{ version }}.tar.gz
  sha256: e735bf05102f6d8aac3cfe444db418bdf4e2a38cc5f7cd02b2c309743b74d206

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - importlib-metadata
    - packaging
  run:
    - python >=3.7
    - importlib-metadata
    - packaging
    - psutil

test:
  imports:
    - enpt_enmapboxapp

about:
  home: https://git.gfz-potsdam.de/EnMAP/GFZ_Tools_EnMAP_BOX/enpt_enmapboxapp
  summary: A QGIS EnMAPBox plugin providing a GUI for the EnMAP processing tool (EnPT).
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
